#!/usr/bin/env python3
"""Regenerate src/assets.rs: the UI files baked into the binary. Run after adding a file under static/."""
import os

MIME = {".html": "text/html; charset=utf-8", ".js": "text/javascript; charset=utf-8",
        ".css": "text/css; charset=utf-8", ".svg": "image/svg+xml", ".png": "image/png",
        ".woff2": "font/woff2", ".ico": "image/x-icon"}
files = []
for root, _, names in os.walk("static"):
    for n in sorted(names):
        p = os.path.join(root, n)
        rel = os.path.relpath(p, "static")
        if os.path.splitext(n)[1] in MIME:
            files.append(rel)
files.sort()
rows = "\n".join(
    f'    ("/{r}", "{MIME[os.path.splitext(r)[1]]}", include_bytes!("../static/{r}")),' for r in files)
open("src/assets.rs", "w").write(f'''//! The UI, baked into the binary. Generated by tools/gen-assets.py; do not edit by hand.
//! While developing, a `static/` folder in the working directory takes precedence (see main::static_file).

/// (url path, content type, contents)
pub const FILES: &[(&str, &str, &[u8])] = &[
{rows}
];
''')
print(f"src/assets.rs: {len(files)} files")
