//! The UI, baked into the binary. Generated by tools/gen-assets.py; do not edit by hand.
//! While developing, a `static/` folder in the working directory takes precedence (see main::static_file).

/// (url path, content type, contents)
pub const FILES: &[(&str, &str, &[u8])] = &[
    ("/app.js", "text/javascript; charset=utf-8", include_bytes!("../static/app.js")),
    ("/index.html", "text/html; charset=utf-8", include_bytes!("../static/index.html")),
    ("/vendor/addons/controls/OrbitControls.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/controls/OrbitControls.js")),
    ("/vendor/addons/postprocessing/EffectComposer.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/EffectComposer.js")),
    ("/vendor/addons/postprocessing/MaskPass.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/MaskPass.js")),
    ("/vendor/addons/postprocessing/OutputPass.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/OutputPass.js")),
    ("/vendor/addons/postprocessing/Pass.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/Pass.js")),
    ("/vendor/addons/postprocessing/RenderPass.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/RenderPass.js")),
    ("/vendor/addons/postprocessing/ShaderPass.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/ShaderPass.js")),
    ("/vendor/addons/postprocessing/UnrealBloomPass.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/postprocessing/UnrealBloomPass.js")),
    ("/vendor/addons/renderers/CSS2DRenderer.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/renderers/CSS2DRenderer.js")),
    ("/vendor/addons/shaders/CopyShader.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/shaders/CopyShader.js")),
    ("/vendor/addons/shaders/LuminosityHighPassShader.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/shaders/LuminosityHighPassShader.js")),
    ("/vendor/addons/shaders/OutputShader.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/addons/shaders/OutputShader.js")),
    ("/vendor/font/manrope-0.woff2", "font/woff2", include_bytes!("../static/vendor/font/manrope-0.woff2")),
    ("/vendor/font/manrope-1.woff2", "font/woff2", include_bytes!("../static/vendor/font/manrope-1.woff2")),
    ("/vendor/font/manrope-2.woff2", "font/woff2", include_bytes!("../static/vendor/font/manrope-2.woff2")),
    ("/vendor/font/manrope-3.woff2", "font/woff2", include_bytes!("../static/vendor/font/manrope-3.woff2")),
    ("/vendor/font/manrope-4.woff2", "font/woff2", include_bytes!("../static/vendor/font/manrope-4.woff2")),
    ("/vendor/font/manrope-5.woff2", "font/woff2", include_bytes!("../static/vendor/font/manrope-5.woff2")),
    ("/vendor/font/manrope.css", "text/css; charset=utf-8", include_bytes!("../static/vendor/font/manrope.css")),
    ("/vendor/three.module.js", "text/javascript; charset=utf-8", include_bytes!("../static/vendor/three.module.js")),
];
