//! The shelf: a folder under ~/.dime where archived items wait, with a manifest that remembers
//! where each one came from so it can be restored in a later session.
use serde::{Deserialize, Serialize};
use std::fs;
use std::os::unix::fs::MetadataExt;
use std::path::{Path, PathBuf};
use std::sync::Mutex;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Serialize, Deserialize, Clone)]
pub struct Entry {
    pub id: String,
    pub name: String,
    /// Absolute original path; restore puts it back here.
    pub from: String,
    pub size: u64,
    pub is_dir: bool,
    #[serde(rename = "shelved_at", alias = "archived_at")]
    pub shelved_at: i64,
    /// Why Di flagged it, e.g. "Build output · Regenerated by the next build".
    pub note: String,
    /// A partial entry holds only some files out of `from` (the idle view moves just the old ones); restore merges them back.
    #[serde(default)]
    pub partial: bool,
    #[serde(default)]
    pub count: u64,
}

static LOCK: Mutex<()> = Mutex::new(());

pub fn dir() -> PathBuf {
    PathBuf::from(std::env::var("HOME").unwrap_or_else(|_| "/tmp".into())).join(".dime").join("shelf")
}
fn manifest() -> PathBuf {
    dir().join("manifest.json")
}
pub fn list() -> Vec<Entry> {
    fs::read(manifest()).ok().and_then(|b| serde_json::from_slice(&b).ok()).unwrap_or_default()
}
fn save(v: &[Entry]) -> std::io::Result<()> {
    fs::create_dir_all(dir())?;
    fs::write(manifest(), serde_json::to_vec_pretty(v)?)
}
fn now() -> i64 {
    SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_secs() as i64
}
fn item_path(e: &Entry) -> PathBuf {
    dir().join(&e.id).join(&e.name)
}

/// Move a path. `rename` is atomic on one volume; across volumes it fails with EXDEV, so fall back to `mv`.
fn mv(from: &Path, to: &Path) -> std::io::Result<()> {
    match fs::rename(from, to) {
        Ok(()) => Ok(()),
        Err(_) => {
            let st = std::process::Command::new("mv").arg(from).arg(to).status()?;
            if st.success() { Ok(()) } else { Err(std::io::Error::other("mv failed")) }
        }
    }
}

pub fn shelve(abs: &Path, size: u64, note: String) -> std::io::Result<Entry> {
    let _g = LOCK.lock().unwrap();
    let md = fs::symlink_metadata(abs)?;
    let name = abs.file_name().map(|n| n.to_string_lossy().into_owned()).ok_or_else(|| std::io::Error::other("no name"))?;
    let id = format!("{:x}", SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos());
    fs::create_dir_all(dir().join(&id))?;
    let e = Entry { id, name, from: abs.to_string_lossy().into_owned(), size, is_dir: md.is_dir(), shelved_at: now(), note, partial: false, count: 1 };
    let mut all = list();
    all.push(e.clone());
    save(&all)?;
    if let Err(err) = mv(abs, &item_path(&e)) {
        all.retain(|x| x.id != e.id);
        let _ = save(&all);
        let _ = fs::remove_dir_all(dir().join(&e.id));
        return Err(err);
    }
    Ok(e)
}

/// Move only some files out of a folder into one shelf entry, keeping their paths relative to it.
pub fn shelve_partial(folder: &Path, files: &[PathBuf], size: u64, note: String) -> std::io::Result<Entry> {
    let _g = LOCK.lock().unwrap();
    let name = folder.file_name().map(|n| n.to_string_lossy().into_owned()).ok_or_else(|| std::io::Error::other("no name"))?;
    let id = format!("{:x}", SystemTime::now().duration_since(UNIX_EPOCH).unwrap().as_nanos());
    let e = Entry { id, name, from: folder.to_string_lossy().into_owned(), size, is_dir: true, shelved_at: now(), note, partial: true, count: files.len() as u64 };
    let mut all = list();
    all.push(e.clone());
    save(&all)?; // listed before anything moves
    let base = item_path(&e);
    let (mut moved, mut bytes) = (0u64, 0u64);
    for rel in files {
        // never `?` in here: an early return would strand the entry saved above, claiming files that
        // never moved. Skip what fails and let the count and size below say what really happened.
        let from = folder.join(rel);
        let Ok(md) = fs::symlink_metadata(&from) else { continue };
        let to = base.join(rel);
        if to.parent().is_some_and(|p| fs::create_dir_all(p).is_err()) {
            continue;
        }
        if mv(&from, &to).is_ok() {
            moved += 1;
            bytes += md.blocks() * 512;
        }
    }
    if moved == 0 {
        all.retain(|x| x.id != e.id);
        let _ = save(&all);
        let _ = fs::remove_dir_all(dir().join(&e.id));
        return Err(std::io::Error::other("nothing could be moved"));
    }
    let e = Entry { count: moved, size: bytes, ..e };
    if let Some(x) = all.iter_mut().find(|x| x.id == e.id) { x.count = moved; x.size = bytes; }
    save(&all)?;
    Ok(e)
}

fn walk_files(dir: &Path, base: &Path, out: &mut Vec<PathBuf>) -> std::io::Result<()> {
    for ent in fs::read_dir(dir)? {
        let p = ent?.path();
        if p.is_dir() { walk_files(&p, base, out)?; } else { out.push(p.strip_prefix(base).unwrap().to_path_buf()); }
    }
    Ok(())
}

/// Put an archived item back where it came from. A whole item refuses if something now lives at that path;
/// a partial one merges its files into the folder and refuses if any of them would overwrite something.
pub fn restore(id: &str) -> std::io::Result<(Entry, Vec<PathBuf>)> {
    let _g = LOCK.lock().unwrap();
    let mut all = list();
    let i = all.iter().position(|e| e.id == id).ok_or_else(|| std::io::Error::other("not in the shelf"))?;
    let e = all[i].clone();
    let to = Path::new(&e.from);
    if e.partial {
        let base = item_path(&e);
        let mut files = vec![];
        walk_files(&base, &base, &mut files)?;
        let clash = files.iter().filter(|r| to.join(r).exists()).count();
        if clash > 0 {
            return Err(std::io::Error::other(format!("{clash} file{} already exist{} again in {}", if clash == 1 { "" } else { "s" }, if clash == 1 { "s" } else { "" }, e.from)));
        }
        for rel in &files {
            let t = to.join(rel);
            if let Some(p) = t.parent() {
                fs::create_dir_all(p)?;
            }
            mv(&base.join(rel), &t)?;
        }
        let _ = fs::remove_dir_all(dir().join(&e.id));
        all.remove(i);
        save(&all)?;
        return Ok((e.clone(), files.iter().map(|r| to.join(r)).collect()));
    } else {
        if to.exists() {
            return Err(std::io::Error::other(format!("something is already at {}", e.from)));
        }
        if let Some(p) = to.parent() {
            fs::create_dir_all(p)?;
        }
        mv(&item_path(&e), to)?;
        let _ = fs::remove_dir(dir().join(&e.id));
    }
    all.remove(i);
    save(&all)?;
    Ok((e.clone(), vec![to.to_path_buf()]))
}

/// Delete an archived item for good.
pub fn purge(id: &str) -> std::io::Result<Entry> {
    let _g = LOCK.lock().unwrap();
    let mut all = list();
    let i = all.iter().position(|e| e.id == id).ok_or_else(|| std::io::Error::other("not in the shelf"))?;
    let e = all.remove(i);
    let d = dir().join(&e.id);
    if d.exists() {
        fs::remove_dir_all(&d)?;
    }
    save(&all)?;
    Ok(e)
}

/// Permanently delete a path on disk (not via the shelf).
pub fn delete(abs: &Path) -> std::io::Result<()> {
    let md = fs::symlink_metadata(abs)?;
    if md.is_dir() { fs::remove_dir_all(abs) } else { fs::remove_file(abs) }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn round_trip() {
        // ponytail: uses the real HOME shelf; run with HOME=$(mktemp -d) to keep it isolated
        let tmp = std::env::temp_dir().join(format!("dime-shelf-test-{}", now()));
        fs::create_dir_all(&tmp).unwrap();
        let f = tmp.join("junk.log");
        fs::write(&f, b"x").unwrap();
        let e = shelve(&f, 1, "test".into()).unwrap();
        assert!(!f.exists() && item_path(&e).exists());
        assert!(list().iter().any(|x| x.id == e.id));
        assert_eq!(restore(&e.id).unwrap().1, vec![f.clone()]);
        assert!(f.exists() && !list().iter().any(|x| x.id == e.id));
        let e = shelve(&f, 1, "test".into()).unwrap();
        purge(&e.id).unwrap();
        assert!(!dir().join(&e.id).exists());
        // partial: two of three files leave a folder and come back, the third never moves
        let d = tmp.join("cache");
        fs::create_dir_all(d.join("sub")).unwrap();
        for n in ["old1", "sub/old2", "fresh"] { fs::write(d.join(n), b"x").unwrap(); }
        let e = shelve_partial(&d, &[PathBuf::from("old1"), PathBuf::from("sub/old2")], 2, "idle".into()).unwrap();
        assert!(e.partial && e.count == 2 && !d.join("old1").exists() && d.join("fresh").exists() && item_path(&e).join("sub/old2").exists());
        assert_eq!(restore(&e.id).unwrap().1.len(), 2);
        assert!(d.join("old1").exists() && d.join("sub/old2").exists() && list().iter().all(|x| x.id != e.id));
        fs::remove_dir_all(&tmp).unwrap();
    }
}
